# Generated by Django 3.1.3 on 2020-11-20 21:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asking', models.TextField()),
                ('answer1', models.CharField(max_length=255)),
                ('answer2', models.CharField(max_length=255)),
                ('answer3', models.CharField(max_length=255)),
                ('answer4', models.CharField(max_length=255)),
                ('right_answer', models.IntegerField(choices=[(1, 'answer1'), (2, 'answer2'), (3, 'answer3'), (4, 'answer4')])),
                ('order', models.PositiveIntegerField()),
                ('created', models.DateTimeField(auto_now=True)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='quizzes.quiz')),
            ],
            options={
                'ordering': ('order',),
            },
        ),
    ]
